import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:shoply/app.dart';
import 'package:shoply/data/services/supabase_service.dart';
import 'package:shoply/data/services/native_oauth_service.dart';
import 'package:shoply/data/services/product_classifier_service.dart';
import 'package:shoply/data/services/gemini_categorization_service.dart';
import 'package:shoply/data/services/analytics_service.dart';
import 'package:shoply/data/services/notification_service.dart';
import 'package:shoply/data/services/fcm_service.dart';
import 'package:shoply/data/services/mascot_notification_service.dart';
import 'package:shoply/data/services/recipe_service.dart';
import 'package:shoply/data/services/app_review_service.dart';
import 'package:shoply/core/services/siri_service.dart';
import 'package:shoply/core/config/env.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:io' show Platform;

/// One-time migration to add labels to recipes
Future<void> _runRecipeLabelMigration() async {
  try {
    final prefs = await SharedPreferences.getInstance();
    const migrationKey = 'recipe_labels_migration_v1';
    
    // Check if migration already ran
    if (prefs.getBool(migrationKey) == true) {
      debugPrint('⏭️ [MIGRATION] Recipe labels migration already completed');
      return;
    }
    
    debugPrint('🔄 [MIGRATION] Running one-time recipe labels migration...');
    final updatedCount = await RecipeService.instance.updateAllRecipesWithLabels();
    
    // Mark migration as complete
    await prefs.setBool(migrationKey, true);
    debugPrint('✅ [MIGRATION] Recipe labels migration complete - updated $updatedCount recipes');
  } catch (e) {
    debugPrint('❌ [MIGRATION] Recipe labels migration failed: $e');
  }
}

void main() async {
  print("🚀🚀🚀 SHOPLY V2.0 NEUE VERSION GESTARTET 🚀🚀🚀");
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Set preferred orientations
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    // Initialize Supabase
    await SupabaseService.initialize();

    // Initialize Firebase with FlutterFire CLI generated options
    if (Platform.isIOS || Platform.isAndroid) {
      try {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
        await AnalyticsService.instance.initialize();
        debugPrint('✅ Firebase Analytics initialized');
      } catch (e) {
        debugPrint('⚠️ Firebase not configured: $e');
        // Continue without Firebase Analytics
      }
    }

    // Initialize Native OAuth Service
    await NativeOAuthService.initialize();

    // Initialize Product Classifier Service
    await ProductClassifierService.instance.initialize();

    // Initialize Gemini Categorization Service with actual API key
    debugPrint('🔵 [MAIN] Initializing Gemini Categorization Service...');
    final geminiService = GeminiCategorizationService();
    await geminiService.initialize(Env.geminiApiKey);
    debugPrint('✅ [MAIN] Gemini Categorization Service initialized');

    // Initialize Siri Service (iOS only)
    if (Platform.isIOS) {
      await SiriService().initialize();
    }

    // Initialize Push Notifications
    if (Platform.isIOS || Platform.isAndroid) {
      debugPrint('🔵 [MAIN] Initializing Notification Service...');
      await NotificationService.instance.initialize();
      debugPrint('🔵 [MAIN] Notification Service initialized: ${NotificationService.instance.isInitialized}');
      
      final permissionGranted = await NotificationService.instance.requestPermissions();
      debugPrint('🔵 [MAIN] Notification permissions granted: $permissionGranted');
      debugPrint('✅ Notification Service initialized and permissions requested');
      
      // Initialize Firebase Cloud Messaging for push notifications
      debugPrint('🔵 [MAIN] Initializing FCM Service...');
      try {
        await FCMService.instance.initialize();
        debugPrint('✅ FCM Service initialized - Token: ${FCMService.instance.token}');
      } catch (e) {
        debugPrint('⚠️ [MAIN] FCM initialization failed (may need GoogleService-Info.plist): $e');
        // Continue without FCM - local notifications will still work
      }
      
      // Track app open for review prompts
      await AppReviewService.instance.trackAppOpen();
    } else {
      debugPrint('⚠️ [MAIN] Skipping notifications - not iOS/Android');
    }

    // Handle deep links for OAuth - this ensures the app returns from browser
    // Also save FCM token when user signs in (handles OAuth flows like Google/Apple)
    Supabase.instance.client.auth.onAuthStateChange.listen((data) async {
      final event = data.event;
      debugPrint('🔐 [AUTH] State changed: $event');
      
      // Save FCM token when user signs in (including OAuth callbacks)
      if (event == AuthChangeEvent.signedIn && (Platform.isIOS || Platform.isAndroid)) {
        debugPrint('🔐 [AUTH] User signed in - saving FCM token');
        await FCMService.instance.saveTokenForCurrentUser();
        
        // Update Avo's last active time and check for notifications
        await MascotNotificationService.instance.updateLastActive();
        await MascotNotificationService.instance.checkAndSendNotification();
        
        // One-time migration: Update recipes with auto-generated labels
        _runRecipeLabelMigration();
      }
    });
  } catch (e) {
    // Log initialization errors silently
  }

  // Run the app
  runApp(
    const ProviderScope(
      child: ShoplyAIApp(),
    ),
  );
}
